#!/bin/bash

# Get the current branch name
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# Update the README.md file with the current branch name
sed -i '' "s|tree/[^ ]*|tree/$BRANCH_NAME|g" README.md

# Add the updated README.md to the commit
git add README.md